version: '3'

services:

  pwc-front-end:
    container_name: pwc-front-end
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    # expose:
    #   - 3000
    ports:
      - "3001:80"
    stdin_open: true